name: Update Credly Badges

on:
  workflow_dispatch: # 수동으로 실행 가능하게 함
  schedule:
    - cron: '0 0 * * *' # 매일 자정(UTC 기준)에 자동 실행

jobs:
  update-readme:
    name: Update Readme with Credly Badges
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update Credly Badges
        uses: eliharper/credly-readme-action@v1.0.3
        with:
          credly_user: daehong-baek # 1단계에서 확인한 ID 입력 (예: kaonmir)
          output_file: README.md # 배지를 추가할 파일 (보통 README.md)
          sort_by: "newest" # 정렬 방식: newest 또는 oldest